DATE_FORMAT = '%Y-%m-%d %H:%M:%S'
SHORT_DATE_FORMAT = '%Y-%m-%d'
MAX_DATE = '9999-12-31 23:59:59'
MIN_DATE = '0001-01-01 00:00:00'
LAST_MONTHS = 3
ROBO_WAIT_TIME = 3
report_file_path = 'reports/report'
companies_file_path = 'sources/companies_list.xlsx'
last_scrape_dates_file_path = 'sources/previous_scrape_dates.json'
